Name: Rex::Framework::Cloudera::Mahout
Description: Installs Mahout
Author: Daniel Baeurer <daniel.baeurer@gmail.com>
License: GPLv3
Require:
   - Rex::Lang::Java
   - Rex::Framework::Cloudera::PkgRepository