Name: Rex::Framework::Cloudera::FlumeNG
Description: Creates and Configure a FlumeNG-Server
Author: Daniel Baeurer <daniel.baeurer@gmail.com>
License: License: GPLv3
Require:
   - Rex::Lang::Java
   - Rex::Framework::Cloudera::PkgRepository
