Name: Rex::Ext::AutoIterate
Description: Automatically iterate over task parameters.
Author: jan gehring <jan.gehring@gmail.com>
License: Apache 2.0
PerlRequire:
   - Devel::Caller
   - Filter::Simple
