Name: Rex::Framework::Cloudera::Hadoop::DataNode
Description: Instantiated and configured a DataNode
Author: Daniel Baeurer <daniel.baeurer@gmail.com>
License: License: GPLv3
Require:
   - Rex::Lang::Java
   - Rex::Framework::Cloudera::PkgRepository
