Name: Rex::Framework::Cloudera::Hadoop::JobTracker
Description: Creates a Hadoop JobTracker node (MRv1 and MRv2)
Author: Daniel Baeurer <daniel.baeurer@gmail.com>
License: License: GPLv3
Require:
   - Rex::Lang::Java
   - Rex::Framework::Cloudera::PkgRepository
