Name: Rex::Framework::Cloudera::Hadoop::HistoryServer
Description: Instantiated and configured a MRv2 HistoryServer
Author: Daniel Baeurer <daniel.baeurer@gmail.com>
License: License: GPLv3
Require:
   - Rex::Lang::Java
   - Rex::Framework::Cloudera::PkgRepository

